version: "3.8"

services:
  server:
    image: node:22
    working_dir: /app/server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: sh -c "npm install && node index.js"
    environment:
      - NODE_ENV=development
    depends_on:
      - client

  client:
    image: node:22
    working_dir: /app/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
